name: all_image_handler
description: The ultimate Flutter image handler. Smart auto-detection (Network, Asset, File, Memory, SVG) with built-in caching, BlurHash, theme-aware shimmer, interactivity (zoom/tap), and premium styling.
version: 0.1.0

homepage: https://github.com/araful39/all_image_handler_package
repository: https://github.com/araful39/all_image_handler_package
issue_tracker: https://github.com/araful39/all_image_handler_package/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - flutter
  - image
  - svg
  - cache
  - network-image

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.9.1
  flutter_svg: ^2.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: