name: all_image_handler
description: A Flutter package that automatically detects and renders images from network, asset, file, memory, SVG, and BlurHash with caching, shimmer loading, retry, error handling, and hero animation support.
version: 0.0.1

homepage: https://github.com/araful39/all_image_handler_package
repository: https://github.com/araful39/all_image_handler_package
issue_tracker: https://github.com/araful39/all_image_handler_package/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - flutter
  - image
  - svg
  - cache
  - network-image

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.9.1
  flutter_svg: ^2.2.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: